PROJECT ?= edk2-cix

src/tools/gcc/gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf.tar.xz:
	mkdir -p src/tools/gcc
	wget -O $@ \
	"https://developer.arm.com/-/media/files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf.tar.xz"

src/tools/gcc/%: src/tools/gcc/%.tar.xz
	tar xvf $< -C src/tools/gcc/

build: build-edk2

.PHONY: build-edk2
build-edk2:
	make -C src

clean: clean-edk2

.PHONY: clean-edk2
clean-edk2:
	make -C src clean
