PROJECT ?= edk2-cix

devcontainer_setup:
	curl -L https://developer.arm.com/-/media/Files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf.tar.xz | sudo tar -xJC /opt

pre_build:
	dos2unix -n src/edk2/BaseTools/Conf/tools_def.template src/edk2/BaseTools/Conf/tools_def.template

post_build:
	unix2dos -n src/edk2/BaseTools/Conf/tools_def.template src/edk2/BaseTools/Conf/tools_def.template

build: build-edk2

.PHONY: build-edk2
build-edk2:
	make -C src

clean: clean-edk2

.PHONY: clean-edk2
clean-edk2:
	make -C src clean
